"""Dependency graph visualization for SupplyShield.

This module renders the dependency topology already produced by the backend
analysis pipeline using PyVis embedded inside Streamlit. It does not build or
recalculate graphs; it only visualizes the graph attached to the supplied
context.
"""

from __future__ import annotations

import json
import logging
from typing import Any

import streamlit as st
from streamlit.components.v1 import html as component_html

try:
    from pyvis.network import Network
except Exception as exc:  # pragma: no cover - exercised only when pyvis is absent
    Network = None  # type: ignore[assignment]
    _PYVIS_IMPORT_ERROR = exc
else:
    _PYVIS_IMPORT_ERROR = None

LOGGER = logging.getLogger(__name__)


def render(context: dict) -> None:
    """Render the existing backend dependency graph inside Streamlit.

    Args:
        context: Analysis context containing the already-built dependency graph.
            The function reads the graph from ``context.graph`` when available.
            If no graph exists, it shows an explanatory placeholder message.
    """
    st.markdown("<div class='page-kicker'>Dependency topology</div>", unsafe_allow_html=True)
    st.title("Dependency graph")
    st.caption("Interactive dependency topology generated by the backend analysis pipeline.")

    try:
        graph = _graph_from_context(context)
    except Exception as exc:
        LOGGER.exception("Unable to read dependency graph from the render context.")
        st.error(f"Unable to render the dependency graph: {exc}")
        return

    if graph is None or graph.number_of_nodes() == 0:
        st.info("Run an analysis to generate the dependency graph.")
        return

    if Network is None:
        LOGGER.exception("PyVis is unavailable for dependency graph rendering.", exc_info=_PYVIS_IMPORT_ERROR)
        st.error("PyVis is required to render the dependency graph.")
        return

    try:
        node_metadata = _build_node_metadata(graph)
        html_content = _build_graph_html(graph, node_metadata)
    except Exception as exc:
        LOGGER.exception("Failed to build dependency graph HTML.")
        st.error(f"Unable to build the dependency graph view: {exc}")
        return

    st.markdown(
        "<div class='section-header'>Interactive topology</div>",
        unsafe_allow_html=True,
    )
    component_html(html_content, height=760, scrolling=False)
    st.markdown(
        "<div class='section-header'>Selection details</div>",
        unsafe_allow_html=True,
    )
    st.markdown(
        "<div class='kpi-card' style='min-height:auto;background:#0F172A;border:1px solid #1E293B; color:#E2E8F0;'>"
        "Hover or click a node to inspect the dependency metadata.</div>",
        unsafe_allow_html=True,
    )


def _graph_from_context(context: dict) -> Any | None:
    """Return the dependency graph from the supplied context without recalculating it."""
    if isinstance(context, dict):
        return context.get("graph")
    return getattr(context, "graph", None)


def _build_node_metadata(graph: Any) -> dict[str, dict[str, Any]]:
    """Prepare display metadata for each graph node."""
    metadata: dict[str, dict[str, Any]] = {}
    for node, attributes in graph.nodes(data=True):
        node_id = str(node)
        library = attributes.get("library") or "N/A"
        version = attributes.get("version") or "N/A"
        dependency_type = attributes.get("dependency_type") or "N/A"
        depth = attributes.get("depth")
        risk_score = attributes.get("risk")
        metadata[node_id] = {
            "id": node_id,
            "label": _node_label(attributes),
            "library": str(library),
            "version": str(version),
            "dependency_type": str(dependency_type),
            "depth": "N/A" if depth is None else str(depth),
            "risk_score": "Not available" if risk_score in (None, "", "N/A") else str(risk_score),
            "node_kind": attributes.get("node_kind", "dependency"),
            "application": attributes.get("application") or "N/A",
        }
    return metadata


def _node_label(attributes: dict[str, Any]) -> str:
    """Create a compact label suitable for the network visualization."""
    if attributes.get("node_kind") == "application":
        application = attributes.get("application") or "Application"
        return str(application)
    library = attributes.get("library") or "Dependency"
    return str(library)


def _build_graph_html(graph: Any, node_metadata: dict[str, dict[str, Any]]) -> str:
    """Generate the HTML snippet needed to render the graph with PyVis."""
    network = Network(
        height="720px",
        width="100%",
        directed=True,
        bgcolor="#07111f",
        font_color="#e2e8f0",
        heading="",
    )
    network.barnes_hut(
        gravity=-1800,
        central_gravity=0.05,
        spring_length=180,
        spring_strength=0.03,
        damping=0.09,
        overlap=0.3,
    )
    network.set_options(
        json.dumps(
            {
                "interaction": {
                    "hover": True,
                    "navigationButtons": True,
                    "keyboard": True,
                    "dragView": True,
                    "zoomView": True,
                    "selectConnectedEdges": False,
                },
                "physics": {
                    "enabled": True,
                    "stabilization": {"iterations": 200},
                },
                "edges": {
                    "color": {"color": "#475569", "highlight": "#60A5FA"},
                    "smooth": False,
                    "width": 1.6,
                },
            }
        )
    )

    for node, attributes in graph.nodes(data=True):
        node_id = str(node)
        metadata = node_metadata[node_id]
        network.add_node(
            node_id,
            label=metadata["label"],
            title=_tooltip_text(metadata),
            color=_node_color(attributes),
            size=24 if attributes.get("node_kind") == "application" else 16,
            shape="dot" if attributes.get("node_kind") == "application" else "ellipse",
            font={"color": "#f8fafc", "face": "Inter", "size": 16},
            borderWidth=2,
        )

    for source, target, _ in graph.edges(data=True):
        network.add_edge(str(source), str(target), color="#64748B")

    html_content = network.generate_html(notebook=False)
    node_metadata_json = json.dumps(node_metadata).replace("</", "<\\/")

    html_content = html_content.replace(
        "</head>",
        """
        <style>
            body { margin: 0; background: #07111f; }
            #mynetwork { background: radial-gradient(circle at top, #14233d 0%, #07111f 70%); border: 1px solid #1e293b; border-radius: 14px; overflow: hidden; }
            .graph-shell { display: flex; flex-direction: column; gap: 12px; }
            .graph-details {
                background: linear-gradient(135deg, #0f172a 0%, #111827 100%);
                border: 1px solid #1e293b;
                border-radius: 12px;
                color: #f8fafc;
                padding: 14px 16px;
                font-family: Inter, Arial, sans-serif;
                box-shadow: 0 20px 50px rgba(2, 8, 23, 0.3);
            }
            .graph-details-title { font-size: 0.92rem; font-weight: 700; color: #60a5fa; margin-bottom: 8px; }
            .graph-details-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr)); gap: 8px; }
            .graph-detail-item { background: rgba(248, 250, 252, 0.04); border: 1px solid rgba(148, 163, 184, 0.16); border-radius: 8px; padding: 8px 10px; }
            .graph-detail-label { display: block; font-size: 0.7rem; letter-spacing: .08em; text-transform: uppercase; color: #94a3b8; margin-bottom: 4px; }
            .graph-detail-value { font-size: 0.9rem; color: #f8fafc; font-weight: 600; word-break: break-word; }
        </style>
        </head>""",
        1,
    )
    html_content = html_content.replace(
        '<div id="mynetwork"></div>',
        '<div class="graph-shell"><div id="graph-details" class="graph-details">Hover or click a node to inspect the dependency metadata.</div><div id="mynetwork"></div></div>',
        1,
    )
    html_content = html_content.replace(
        "</body>",
        f"""
        <script>
        document.addEventListener('DOMContentLoaded', function() {{
            const detailsElement = document.getElementById('graph-details');
            const nodeMetadata = {node_metadata_json};
            if (!detailsElement || typeof network === 'undefined') {{
                return;
            }}
            const resetDetails = function() {{
                detailsElement.innerHTML = '<div class=\"graph-details-title\">Dependency details</div><div class=\"graph-detail-item\"><span class=\"graph-detail-label\">Hint</span><span class=\"graph-detail-value\">Hover or click a node to inspect the dependency metadata.</span></div>';
            }};
            const updateDetails = function(nodeId) {{
                const metadata = nodeMetadata[nodeId];
                if (!metadata) {{
                    resetDetails();
                    return;
                }}
                detailsElement.innerHTML = [
                    '<div class=\"graph-details-title\">' + escapeHtml(metadata.label) + '</div>',
                    '<div class=\"graph-details-grid\">',
                    '<div class=\"graph-detail-item\"><span class=\"graph-detail-label\">Library</span><span class=\"graph-detail-value\">' + escapeHtml(metadata.library) + '</span></div>',
                    '<div class=\"graph-detail-item\"><span class=\"graph-detail-label\">Version</span><span class=\"graph-detail-value\">' + escapeHtml(metadata.version) + '</span></div>',
                    '<div class=\"graph-detail-item\"><span class=\"graph-detail-label\">Dependency Type</span><span class=\"graph-detail-value\">' + escapeHtml(metadata.dependency_type) + '</span></div>',
                    '<div class=\"graph-detail-item\"><span class=\"graph-detail-label\">Depth</span><span class=\"graph-detail-value\">' + escapeHtml(metadata.depth) + '</span></div>',
                    '<div class=\"graph-detail-item\"><span class=\"graph-detail-label\">Risk Score</span><span class=\"graph-detail-value\">' + escapeHtml(metadata.risk_score) + '</span></div>',
                    '</div>'
                ].join('');
            }};
            const escapeHtml = function(value) {{
                return String(value)
                    .replace(/&/g, '&amp;')
                    .replace(/</g, '&lt;')
                    .replace(/>/g, '&gt;')
                    .replace(/\"/g, '&quot;')
                    .replace(/'/g, '&#39;');
            }};
            network.on('hoverNode', function(params) {{
                updateDetails(params.node);
            }});
            network.on('blurNode', function() {{
                resetDetails();
            }});
            network.on('click', function(params) {{
                if (params.nodes.length) {{
                    updateDetails(params.nodes[0]);
                }}
            }});
            resetDetails();
        }});
        </script>
        </body>""",
        1,
    )
    return html_content


def _node_color(attributes: dict[str, Any]) -> str:
    """Choose a node color appropriate for the dependency kind."""
    if attributes.get("node_kind") == "application":
        return "#38BDF8"
    dependency_type = str(attributes.get("dependency_type", "")).casefold()
    if dependency_type == "direct":
        return "#60A5FA"
    if dependency_type == "transitive":
        return "#A78BFA"
    return "#34D399"


def _tooltip_text(metadata: dict[str, Any]) -> str:
    """Create a hover tooltip for a node."""
    return (
        f"Library: {metadata['library']}\n"
        f"Version: {metadata['version']}\n"
        f"Dependency Type: {metadata['dependency_type']}\n"
        f"Depth: {metadata['depth']}\n"
        f"Risk Score: {metadata['risk_score']}"
    )
