"""Display already-generated SupplyShield reports and exports.

This module does not generate new artifacts. It inspects the existing generated
files in the repository and presents them for download through Streamlit.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import streamlit as st

from dashboard.shared import AnalysisBundle, application_selector

LOGGER = logging.getLogger(__name__)

_ROOT = Path(__file__).resolve().parent.parent
_REPORTS_DIR = _ROOT / "generated" / "reports"
_EXPORTS_DIR = _ROOT / "generated" / "exports"


def render(context: AnalysisBundle) -> None:
    """Render already-generated portfolio reports and exports from disk.

    Args:
        context: Render context provided by the application. The function only
            reads the context for compatibility and does not use it otherwise.
    """
    st.markdown("<div class='page-kicker'>Reports & exports</div>", unsafe_allow_html=True)
    st.title("Reports")
    st.caption("Download the reports and CSV exports already generated by SupplyShield.")
    selected_application = application_selector(context, key="reports_application_scope")

    try:
        portfolio_pdfs = _discover_files(_REPORTS_DIR, suffix=".pdf")
        csv_exports = _discover_files(_EXPORTS_DIR, suffix=".csv")
    except Exception as exc:
        LOGGER.exception("Unable to inspect report directories.")
        st.error(f"Unable to load reports: {exc}")
        return

    if not portfolio_pdfs and not csv_exports:
        st.info("No reports generated yet. Run SupplyShield analysis first.")
        return

    if selected_application is not None:
        scope = _safe_name(selected_application)
        portfolio_pdfs = [item for item in portfolio_pdfs if scope in item["name"].casefold()]
        csv_exports = [item for item in csv_exports if scope in item["name"].casefold()]
        if not portfolio_pdfs and not csv_exports:
            st.info(f"No existing report artifacts are scoped to {selected_application}.")
            return
    _render_section("PDF reports", portfolio_pdfs)
    _render_section("CSV exports", csv_exports)


def _discover_files(directory: Path, suffix: str) -> list[dict[str, Any]]:
    """Return sorted report metadata for files that exist in a directory."""
    if not directory.exists():
        return []

    files: list[dict[str, Any]] = []
    for path in sorted(directory.iterdir()):
        if path.is_file() and path.suffix.lower() == suffix.lower():
            try:
                stat = path.stat()
                timestamp = _format_timestamp(stat.st_mtime)
            except OSError as exc:
                LOGGER.warning("Unable to read metadata for %s: %s", path, exc)
                timestamp = "Unknown"
            files.append({"path": path, "name": path.name, "timestamp": timestamp})
    return files


def _format_timestamp(epoch_seconds: float) -> str:
    """Return a readable timestamp for a file's modification time."""
    from datetime import datetime

    return datetime.fromtimestamp(epoch_seconds).strftime("%Y-%m-%d %H:%M:%S")


def _render_section(title: str, files: list[dict[str, Any]]) -> None:
    """Render a card-like section for one group of report artifacts."""
    if not files:
        return

    st.markdown(
        f"<div class='section-header'>{title}</div>",
        unsafe_allow_html=True,
    )

    for item in files:
        card = st.container()
        with card:
            st.markdown(
                "<div class='kpi-card' style='min-height:auto;'>"
                f"<div class='kpi-label'>{item['name']}</div>"
                f"<div class='kpi-meta'>Generated {item['timestamp']}</div>"
                "</div>",
                unsafe_allow_html=True,
            )
            with open(item["path"], "rb") as handle:
                st.download_button(
                    label="Download",
                    data=handle.read(),
                    file_name=item["name"],
                    mime=_mime_type(item["path"]),
                    use_container_width=True,
                )


def _mime_type(path: Path) -> str:
    """Return the MIME type for a report file."""
    if path.suffix.lower() == ".pdf":
        return "application/pdf"
    if path.suffix.lower() == ".csv":
        return "text/csv"
    return "application/octet-stream"


def _safe_name(value: str) -> str:
    """Match the report generator's filesystem-safe application-name format."""
    import re

    return re.sub(r"[^a-z0-9]+", "_", value.casefold()).strip("_")
